# Generated by Django 3.0.2 on 2020-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
