# Generated by Django 3.0.2 on 2020-08-08 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Number should be 10 digit', regex='[1-9]{1}[0-9]{9}')]),
        ),
    ]
