# Generated by Django 3.0.2 on 2020-08-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20200808_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='annual_income',
            field=models.CharField(blank=True, choices=[('100000', '<100000'), ('100000-300000', '100000-300000'), ('300000-600000', '300000-600000'), ('600000-1000000', '600000-1000000'), ('1000000-1500000', '1000000-1500000'), ('1500000-2000000', '1500000-2000000'), ('>2000000', '>2000000')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthplace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('-A', '-A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Black', 'Black'), ('Brown', 'Brown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='caste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Single', 'Single')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Meitei (Manipuri)', 'Meitei (Manipuri)'), ('Nepali', 'Nepali'), ('Odia', 'Odia'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santali', 'Santali')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='navaras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Buddhism', 'Buddhism'), ('Jainism', 'Jainism'), ('Zoroastrianism', 'Zoroastrianism')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_caste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
