# Generated by Django 3.0.2 on 2020-08-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
